config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'welcome/index'

  resources :sessions
  resources :users

   root 'welcome#index'
    resources :articles
    resources :categories
    resources :welcome
    resources :users

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories 
	validates :title, presence: true
	validates :content, presence: true
	validates :categories, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article 
	belongs_to :category 
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :articles  #a user can own many articles in DB
	validates_uniqueness_of :email  #email has to be unique
	validates :name, presence: true #and these fields need to be filled in
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_categories

  def authorize
  	redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  private
  def get_categories
  	@categories = Category.all.order(:name)
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	before_filter :authorize, only: [:new]
	
	def index
		@articles = Article.order(updated_at: :desc).limit(25)
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render "new"
		end
	end

	private
		def article_params
			params.require(:article).permit(:title, :content, :category_ids => [])
		end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	#lists all article categories by alphabetical order ascending
	def index
		@categories = Category.all.order(name: :desc)
	end

	#takes to a separate page and lists all articles within that category
	def show
		@category = Category.find(params[:id])
	end

end	

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password]) # has_secure_password built this in
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Logged in"
  	else
  		flash.now.alert = "Email or password is invalid"
  		render "new"
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "You are now logged out"
  end

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new #IS THIS "USER" from models?
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Thank you for signing up."
		else
			render "new" #What does NEW actually render?
		end
	end

	private
		def user_params
			params.require(:user).permit(:email, :name, :password, :password_confirmation)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@recent_articles = Article.order(updated_at: :desc).limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>This is the index view for Articles</h1>
<% @articles.each do |article| %>
	<div>
		<h3><%= link_to article.title, article %></h3>
			<p>Published on <%= article.created_at.strftime('%b %d, %Y') %></p>
		<p>Filed under: <% article.categories.each do |category| %>
							<%= category.name %>&nbsp;
						<% end %>
		</p>
		<p><%= truncate(article.content, length: 200) %></p>
	</div>
<% end %>

app/views/articles/mattsthebest.html.erb
<%= @somethingelse %>
<% i = "Burger King is better." %>
<%= i %>

app/views/articles/new.html.erb
<h1>Write and Publish a New Article</h1>
<% if @article.errors.any? %>
	<div class= "error_messages">
		<h2>You're missing some fields</h2>
		<ul>
			<% @article.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<div>
	<h1><%= @article.title %></h1>
	<p>Published <%= @article.created_at.strftime('%b %d, %Y') %></p>
	<p>Filed under: <% @article.categories.each do |category| %>
		<%= category.name %>&nbsp;<% end %>
	</p>
	<div><%= @article.content %></div>
</div>

app/views/categories/index.html.erb
<h1>This is the index view for Categories</h1>
	<% @categories.each do |category| %>
		<div>
			<h3><%= link_to category.name, category %></h3>
		</div>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %> Articles</h1>
 <h3>There are <%= @category.articles.count %> articles filed under <%= @category.name %></h3>
 <ul>
 	<% @category.articles.order(:title).each do |article| %>
 		<h4>
 	  	<%= link_to article.title, article %>
 	  </h4>
 	<% end %>
 </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikiful</title>
  	<!--[if lt IE 9]>
  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head> 
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Wikiful", root_path, :class => "brand" %>
				<div class='session-controls'>
					<% if current_user %>
						<%= link_to "Log Out", logout_path, :class => 'btn btn-primary btn-mini' %>						Logged in as <%= current_user.email %>.
					<% else %>
						<div class="btn-group">
							<%= link_to "Sign Up", signup_path, :class => "btn btn-mini" %>
							<%= link_to "Log In", login_path, :class => "btn btn-mini" %>
						</div>
					<% end %> 
				</div>
			</div>
		</div>
	</div>

<div class="row">
	<div class="span4">
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, id: "flash_#{name}" %>
		<% end %>
	</div>
</div>

<div class="span3 sidebar">
	<div class="my-wiki-site">
		<img src="http://2.bp.blogspot.com/-qSBLtcVU-h0/UL_1BwC1l_I/AAAAAAAABjg/6NCOAQfX9MY/s1600/m123194294.gif" width="171" height="313">
		<li class="nav-header" font_size: >Wikiful</li>
		<ul>
			<li><%= link_to "Write a Wiki", new_article_path %></li>
		</ul>
	</div>
<div class="categories-sidebar">
	<li class="nav-header">Categories</li>
		<ul class="nav nav-list">
			<% @categories.each do |category| %>
				<li><%= link_to category.name, category %></li>
			<% end %>
		</ul>
	</div>
<div class="about">
	<h4>About Wikiful</h4>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto earum neque perspiciatis quia animi debitis quod repellat vitae explicabo. Sapiente aliquam reprehenderit id vitae atque ducimus facere molestias soluta?</p>
	</div>
</div>
<%= yield %> 

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class='field'>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class='field'>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div class='field'>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div class='field'>
		<%= f.label :password_confirmations %>
		<%= f.password_field :password_confirmations %>
	</div>
	<div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Wikiful</h1>
<p>The world's knowledge of Pig Latin at your fingertips</p>
<% @recent_articles.each do |article| %>
	<div>
		<h3><%= link_to article.title, article %></h3>
			<a class="btn btn-default btn-lg" disabled="disabled" >Published on <%= article.created_at.strftime('%b %d, %Y') %></a>
			<p class="btn btn-link">Filed under: <% article.categories.each do |category| %>
					<%= category.name%>&nbsp;
				<% end %>
			</p>
			<p><%= truncate(article.content,length: 300) %></p>	
	</div>
<% end %>